### PR TITLE
Adds Kammerl Beat Repeat to Parasites

### PR DESCRIPTION
**Pull request by boourns**
This just ports Julius's beat repeat code into Parasites.  I generated a patch based on the last two commits of this fork https://github.com/jkammerl/eurorack/commits/master

There is no size problem as far as I can tell.  It compiles and uploads fine, all modes play, buffer saving/restoring works fine.

There's a bit of work I still need to do - reverb is still enabled on the beat-repeat algorithm, and I want to go through the patch one more time to ensure that I didn't miss anything else.  It could use some people testing it too to ensure it performs the same as the isolated firmware.

I haven't played with the spectral clouds algorithm much - would it be worth also implementing that as an additional algorithm, or replacing spectral mode, or leave it be?

### CODE REVIEW

**Comment by boourns** [comment]
@mqtthiqs @jkammerl hi guys

if I polish this up are you cool with merging it, or do you want to keep these firmwares separate?

**Comment by unity2k** [comment]
My hope is that @mqtthiqs and @jkammerl would also like to see the merger. I'd also like to vote in the affirmative for Spectral Clouds to be included.

**Comment by mqtthiqs** [comment]
Hi there, thanks for your work @boourns. I'm really happy that someone is still improving this, and kammerl's modes look really interesting. That said, I'd rather have this development not take place in my repository: I am not maintaining this project anymore and I don't want to be held responsible for the changes, releases, bug fixes etc. Feel free to clone and advertise you own repository with the merge though!

**Comment by boourns** [comment]
OK, thanks @mqtthiqs!

I'll close this here and figure out my next steps.  Cheers.

**Comment by naught101** [comment]
@boourns did you give up on this? I would love to try it, but it would probably take me a bit to ramp up to compiling it. Is there a wav file available anywhere?

**Comment by naught101** [comment]
Oh yeah, here: https://www.muffwiggler.com/forum/viewtopic.php?p=2630741&sid=26153d05d88ba34fd42f821ad6d97a88#2630741

**Comment by naught101** [comment]
Argh, but that firmware doesn't work well for Monsoon. @boourns what would be involved in making the combined firmware work for Monsoon?

**Comment by boourns** [comment]
I don't have time to do this / test it but since I DID also write the Monsoon firmware changes, I'll try to point you in the right direction.

Basically you need to take this jkammerl/parasites branch, and apply the 3 commits I wrote here:
https://github.com/boourns/eurorack/commits/parasites

then compile and you should be set.

Give it a shot and let me know how it goes.

Note that this firmware is VERY close to full ROM.  In fact, after I wrote this, I tried starting with a stock firmware and adding all the modes, and ran out of space long before I was done.

**Pull request closed without merging**
